-- مولّد بـ tools/build_ifada_rules.py من refs/rules_v2.json (الإصدار 2.1) فلا يُعدَّل يدوياً
begin;
delete from public.ifada_rules;
insert into public.ifada_rules(code,src,mand,pending) values
('SETBACK-01','RES',true,false),
('SETBACK-02','RES',true,false),
('SETBACK-03','RES',true,false),
('COVER-01','RES',true,false),
('COVER-02','RES',true,false),
('ANNEX-01','RES',true,false),
('HEIGHT-01','RES',true,false),
('LEVEL-01','RES',true,false),
('PARAPET-01','RES',true,false),
('PARK-01','RES',true,false),
('PARK-02','RES',true,false),
('ROOM-MIN-01','RES',true,false),
('CORR-01','RES',true,false),
('DOOR-01','RES',true,false),
('LIGHT-01','RES',true,false),
('LIGHT-02','RES',true,false),
('SHAFT-01','RES',true,false),
('STAIR-01','RES',true,false),
('RAIL-01','RES',true,false),
('SERV-01','RES',true,false),
('PROJ-01','RES',true,false),
('CHAMF-01','RES',true,false),
('PLAN-01','RES',true,false),
('SETBACK-04','RES',true,false),
('SETBACK-05','RES',true,false),
('ZEROLOT-01','RES',true,false),
('SPLIT-01','RES',true,false),
('GANNEX-01','RES',true,false),
('FENCE-01','RES',true,false),
('DRIVER-01','RES',true,false),
('SETROOF-01','RES',true,false),
('STEP-01','RES',true,false),
('BSMT-01','RES',true,false),
('PARK-04','RES',true,false),
('PARK-08','RES',true,false),
('PARK-12','RES',false,false),
('SAFE-01','RES',true,false),
('DRAIN-01','RES',true,false),
('SHAFT-02','RES',true,false),
('BALC-01','RES',true,false),
('STAIR-02','RES',true,false),
('STAIR-03','RES',true,false),
('TERRAIN-01','RES',true,false),
('FACADE-01','RES',false,false),
('ANNEX-02','RES',true,false),
('KITCHEN-02','RES',true,false),
('SKYLIGHT-01','RES',true,false),
('SEPTIC-01','RES',true,false),
('UNIT-01','RES',true,false),
('ACCESS-00','RES',false,false),
('EGRESS-01','SBC',true,true),
('STAIR-04','SBC',true,false),
('STAIR-05','SBC',true,true),
('CEIL-01','SBC',true,true),
('GUARD-02','SBC',true,false),
('WINFALL-01','SBC',true,false);
insert into public.ifada_sources(id,title,publisher,edition,ord) values
('RES','اشتراطات إنشاء المباني السكنية','وزارة البلديات والإسكان','1446هـ/2024م',1),
('SBC','الكود السعودي للمباني السكنية SBC 1101','المركز الوطني لكود البناء','2024',2)
on conflict (id) do update set title=excluded.title,publisher=excluded.publisher,edition=excluded.edition,ord=excluded.ord;
commit;
